name: 'Amazon Batch "Render Job Definition" Action for GitHub Actions'
description: "Inserts a container image URI into a an Amazon Batch job definition JSON file, creating a new file."
branding:
  icon: "cloud"
  color: "orange"
inputs:
  job-definition:
    description: "The path to the Batch job definition JSON file"
    required: false
  job-definition-name:
    description: "The name of the Batch job definition to update"
    required: false
  image:
    description: "The URI of the container image to insert into the Batch job definition"
    required: true
  command-to-override:
    description: "The command to override in the job definition (e.g. 'python -m src.main')"
    required: false
  exclude-tags:
    description: "Comma-separated list of tag keys to exclude from the rendered job definition"
    required: false
outputs:
  job-definition:
    description: "The path to the rendered task definition file"
runs:
  using: "node24"
  main: "dist/index.js"
